### PR TITLE
new: hot reload functionallity

### PR DESCRIPTION
**Pull request by DonutEspresso**
Continuation of #13.

### CODE REVIEW

**Comment by DonutEspresso** [comment]
@yunong this might be a good place to help out with - this would be a huge win for devprod immediately. Open questions:

* should the hot reload configuration be an enroute schema configuration or a runtime option when you call `install`? (I prefer latter)
* are the typed errors a major breaking change? (I prefer yes)
* what's a good way to add a test for this? (add a test that changes the response payload and verify it that way?)

Also need to update README

**Comment by yunong** [comment]
@DonutEspresso Landed tests and docs.

**Comment by DonutEspresso** [comment]
Wah wah, fs-extra breaks on node4 due to some ES6 syntax. It looks like a dev time dependency only, are there other alternatives? Or we can make this a breaking change for enroute by dropping node4 support?

**Comment by yunong** [comment]
Already dropped v4 support ;)

**Review by DonutEspresso — COMMENTED** [review]
lgtm. is this a new major version then?

**Comment by yunong** [comment]
Looks like it

**Pull request merged**
